package it.etoken.component.market.dao.mapper;

import it.etoken.base.model.market.entity.Coins;
import it.etoken.base.model.market.entity.CoinsExample.Criteria;
import it.etoken.base.model.market.entity.CoinsExample.Criterion;
import it.etoken.base.model.market.entity.CoinsExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class CoinsSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coins
	 * @mbg.generated  Mon Aug 20 16:15:02 CST 2018
	 */
	public String countByExample(CoinsExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("coins");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coins
	 * @mbg.generated  Mon Aug 20 16:15:02 CST 2018
	 */
	public String deleteByExample(CoinsExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("coins");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coins
	 * @mbg.generated  Mon Aug 20 16:15:02 CST 2018
	 */
	public String insertSelective(Coins record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("coins");
		if (record.getId() != null) {
			sql.VALUES("id", "#{id,jdbcType=BIGINT}");
		}
		if (record.getName() != null) {
			sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
		}
		if (record.getCreatedate() != null) {
			sql.VALUES("createdate", "#{createdate,jdbcType=TIMESTAMP}");
		}
		if (record.getModifydate() != null) {
			sql.VALUES("modifydate", "#{modifydate,jdbcType=TIMESTAMP}");
		}
		if (record.getSite() != null) {
			sql.VALUES("site", "#{site,jdbcType=VARCHAR}");
		}
		if (record.getIntr() != null) {
			sql.VALUES("intr", "#{intr,jdbcType=VARCHAR}");
		}
		if (record.getImg() != null) {
			sql.VALUES("img", "#{img,jdbcType=VARCHAR}");
		}
		if (record.getTag() != null) {
			sql.VALUES("tag", "#{tag,jdbcType=VARCHAR}");
		}
		if (record.getTotal() != null) {
			sql.VALUES("total", "#{total,jdbcType=BIGINT}");
		}
		if (record.getMarke() != null) {
			sql.VALUES("marke", "#{marke,jdbcType=BIGINT}");
		}
		if (record.getCode() != null) {
			sql.VALUES("code", "#{code,jdbcType=VARCHAR}");
		}
		if (record.getSymble() != null) {
			sql.VALUES("symble", "#{symble,jdbcType=VARCHAR}");
		}
		if (record.getContractAccount() != null) {
			sql.VALUES("contract_account", "#{contractAccount,jdbcType=VARCHAR}");
		}
		if (record.getIsSupportMarket() != null) {
			sql.VALUES("is_support_market", "#{isSupportMarket,jdbcType=VARCHAR}");
		}
		if (record.getPrecisionNumber() != null) {
			sql.VALUES("precision_number", "#{precisionNumber,jdbcType=INTEGER}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coins
	 * @mbg.generated  Mon Aug 20 16:15:02 CST 2018
	 */
	public String selectByExample(CoinsExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("id");
		} else {
			sql.SELECT("id");
		}
		sql.SELECT("name");
		sql.SELECT("createdate");
		sql.SELECT("modifydate");
		sql.SELECT("site");
		sql.SELECT("intr");
		sql.SELECT("img");
		sql.SELECT("tag");
		sql.SELECT("total");
		sql.SELECT("marke");
		sql.SELECT("code");
		sql.SELECT("symble");
		sql.SELECT("contract_account");
		sql.SELECT("is_support_market");
		sql.SELECT("precision_number");
		sql.FROM("coins");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coins
	 * @mbg.generated  Mon Aug 20 16:15:02 CST 2018
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		Coins record = (Coins) parameter.get("record");
		CoinsExample example = (CoinsExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("coins");
		if (record.getId() != null) {
			sql.SET("id = #{record.id,jdbcType=BIGINT}");
		}
		if (record.getName() != null) {
			sql.SET("name = #{record.name,jdbcType=VARCHAR}");
		}
		if (record.getCreatedate() != null) {
			sql.SET("createdate = #{record.createdate,jdbcType=TIMESTAMP}");
		}
		if (record.getModifydate() != null) {
			sql.SET("modifydate = #{record.modifydate,jdbcType=TIMESTAMP}");
		}
		if (record.getSite() != null) {
			sql.SET("site = #{record.site,jdbcType=VARCHAR}");
		}
		if (record.getIntr() != null) {
			sql.SET("intr = #{record.intr,jdbcType=VARCHAR}");
		}
		if (record.getImg() != null) {
			sql.SET("img = #{record.img,jdbcType=VARCHAR}");
		}
		if (record.getTag() != null) {
			sql.SET("tag = #{record.tag,jdbcType=VARCHAR}");
		}
		if (record.getTotal() != null) {
			sql.SET("total = #{record.total,jdbcType=BIGINT}");
		}
		if (record.getMarke() != null) {
			sql.SET("marke = #{record.marke,jdbcType=BIGINT}");
		}
		if (record.getCode() != null) {
			sql.SET("code = #{record.code,jdbcType=VARCHAR}");
		}
		if (record.getSymble() != null) {
			sql.SET("symble = #{record.symble,jdbcType=VARCHAR}");
		}
		if (record.getContractAccount() != null) {
			sql.SET("contract_account = #{record.contractAccount,jdbcType=VARCHAR}");
		}
		if (record.getIsSupportMarket() != null) {
			sql.SET("is_support_market = #{record.isSupportMarket,jdbcType=VARCHAR}");
		}
		if (record.getPrecisionNumber() != null) {
			sql.SET("precision_number = #{record.precisionNumber,jdbcType=INTEGER}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coins
	 * @mbg.generated  Mon Aug 20 16:15:02 CST 2018
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("coins");
		sql.SET("id = #{record.id,jdbcType=BIGINT}");
		sql.SET("name = #{record.name,jdbcType=VARCHAR}");
		sql.SET("createdate = #{record.createdate,jdbcType=TIMESTAMP}");
		sql.SET("modifydate = #{record.modifydate,jdbcType=TIMESTAMP}");
		sql.SET("site = #{record.site,jdbcType=VARCHAR}");
		sql.SET("intr = #{record.intr,jdbcType=VARCHAR}");
		sql.SET("img = #{record.img,jdbcType=VARCHAR}");
		sql.SET("tag = #{record.tag,jdbcType=VARCHAR}");
		sql.SET("total = #{record.total,jdbcType=BIGINT}");
		sql.SET("marke = #{record.marke,jdbcType=BIGINT}");
		sql.SET("code = #{record.code,jdbcType=VARCHAR}");
		sql.SET("symble = #{record.symble,jdbcType=VARCHAR}");
		sql.SET("contract_account = #{record.contractAccount,jdbcType=VARCHAR}");
		sql.SET("is_support_market = #{record.isSupportMarket,jdbcType=VARCHAR}");
		sql.SET("precision_number = #{record.precisionNumber,jdbcType=INTEGER}");
		CoinsExample example = (CoinsExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coins
	 * @mbg.generated  Mon Aug 20 16:15:02 CST 2018
	 */
	public String updateByPrimaryKeySelective(Coins record) {
		SQL sql = new SQL();
		sql.UPDATE("coins");
		if (record.getName() != null) {
			sql.SET("name = #{name,jdbcType=VARCHAR}");
		}
		if (record.getCreatedate() != null) {
			sql.SET("createdate = #{createdate,jdbcType=TIMESTAMP}");
		}
		if (record.getModifydate() != null) {
			sql.SET("modifydate = #{modifydate,jdbcType=TIMESTAMP}");
		}
		if (record.getSite() != null) {
			sql.SET("site = #{site,jdbcType=VARCHAR}");
		}
		if (record.getIntr() != null) {
			sql.SET("intr = #{intr,jdbcType=VARCHAR}");
		}
		if (record.getImg() != null) {
			sql.SET("img = #{img,jdbcType=VARCHAR}");
		}
		if (record.getTag() != null) {
			sql.SET("tag = #{tag,jdbcType=VARCHAR}");
		}
		if (record.getTotal() != null) {
			sql.SET("total = #{total,jdbcType=BIGINT}");
		}
		if (record.getMarke() != null) {
			sql.SET("marke = #{marke,jdbcType=BIGINT}");
		}
		if (record.getCode() != null) {
			sql.SET("code = #{code,jdbcType=VARCHAR}");
		}
		if (record.getSymble() != null) {
			sql.SET("symble = #{symble,jdbcType=VARCHAR}");
		}
		if (record.getContractAccount() != null) {
			sql.SET("contract_account = #{contractAccount,jdbcType=VARCHAR}");
		}
		if (record.getIsSupportMarket() != null) {
			sql.SET("is_support_market = #{isSupportMarket,jdbcType=VARCHAR}");
		}
		if (record.getPrecisionNumber() != null) {
			sql.SET("precision_number = #{precisionNumber,jdbcType=INTEGER}");
		}
		sql.WHERE("id = #{id,jdbcType=BIGINT}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coins
	 * @mbg.generated  Mon Aug 20 16:15:02 CST 2018
	 */
	protected void applyWhere(SQL sql, CoinsExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}