package it.etoken.component.market.dao.mapper;

import it.etoken.base.model.market.entity.PocketAsset;
import it.etoken.base.model.market.entity.PocketAssetExample.Criteria;
import it.etoken.base.model.market.entity.PocketAssetExample.Criterion;
import it.etoken.base.model.market.entity.PocketAssetExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class PocketAssetSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pocket_asset
	 * @mbg.generated  Mon Jun 25 20:07:10 CST 2018
	 */
	public String countByExample(PocketAssetExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("pocket_asset");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pocket_asset
	 * @mbg.generated  Mon Jun 25 20:07:10 CST 2018
	 */
	public String deleteByExample(PocketAssetExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("pocket_asset");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pocket_asset
	 * @mbg.generated  Mon Jun 25 20:07:10 CST 2018
	 */
	public String insertSelective(PocketAsset record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("pocket_asset");
		if (record.getId() != null) {
			sql.VALUES("id", "#{id,jdbcType=BIGINT}");
		}
		if (record.getName() != null) {
			sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
		}
		if (record.getIcon() != null) {
			sql.VALUES("icon", "#{icon,jdbcType=VARCHAR}");
		}
		if (record.getContractAccount() != null) {
			sql.VALUES("contract_account", "#{contractAccount,jdbcType=VARCHAR}");
		}
		if (record.getCreateDate() != null) {
			sql.VALUES("create_date", "#{createDate,jdbcType=TIMESTAMP}");
		}
		if (record.getUpdateDate() != null) {
			sql.VALUES("update_date", "#{updateDate,jdbcType=TIMESTAMP}");
		}
		if (record.getDetail() != null) {
			sql.VALUES("detail", "#{detail,jdbcType=LONGVARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pocket_asset
	 * @mbg.generated  Mon Jun 25 20:07:10 CST 2018
	 */
	public String selectByExampleWithBLOBs(PocketAssetExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("id");
		} else {
			sql.SELECT("id");
		}
		sql.SELECT("name");
		sql.SELECT("icon");
		sql.SELECT("contract_account");
		sql.SELECT("create_date");
		sql.SELECT("update_date");
		sql.SELECT("detail");
		sql.FROM("pocket_asset");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pocket_asset
	 * @mbg.generated  Mon Jun 25 20:07:10 CST 2018
	 */
	public String selectByExample(PocketAssetExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("id");
		} else {
			sql.SELECT("id");
		}
		sql.SELECT("name");
		sql.SELECT("icon");
		sql.SELECT("contract_account");
		sql.SELECT("create_date");
		sql.SELECT("update_date");
		sql.FROM("pocket_asset");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pocket_asset
	 * @mbg.generated  Mon Jun 25 20:07:10 CST 2018
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		PocketAsset record = (PocketAsset) parameter.get("record");
		PocketAssetExample example = (PocketAssetExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("pocket_asset");
		if (record.getId() != null) {
			sql.SET("id = #{record.id,jdbcType=BIGINT}");
		}
		if (record.getName() != null) {
			sql.SET("name = #{record.name,jdbcType=VARCHAR}");
		}
		if (record.getIcon() != null) {
			sql.SET("icon = #{record.icon,jdbcType=VARCHAR}");
		}
		if (record.getContractAccount() != null) {
			sql.SET("contract_account = #{record.contractAccount,jdbcType=VARCHAR}");
		}
		if (record.getCreateDate() != null) {
			sql.SET("create_date = #{record.createDate,jdbcType=TIMESTAMP}");
		}
		if (record.getUpdateDate() != null) {
			sql.SET("update_date = #{record.updateDate,jdbcType=TIMESTAMP}");
		}
		if (record.getDetail() != null) {
			sql.SET("detail = #{record.detail,jdbcType=LONGVARCHAR}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pocket_asset
	 * @mbg.generated  Mon Jun 25 20:07:10 CST 2018
	 */
	public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("pocket_asset");
		sql.SET("id = #{record.id,jdbcType=BIGINT}");
		sql.SET("name = #{record.name,jdbcType=VARCHAR}");
		sql.SET("icon = #{record.icon,jdbcType=VARCHAR}");
		sql.SET("contract_account = #{record.contractAccount,jdbcType=VARCHAR}");
		sql.SET("create_date = #{record.createDate,jdbcType=TIMESTAMP}");
		sql.SET("update_date = #{record.updateDate,jdbcType=TIMESTAMP}");
		sql.SET("detail = #{record.detail,jdbcType=LONGVARCHAR}");
		PocketAssetExample example = (PocketAssetExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pocket_asset
	 * @mbg.generated  Mon Jun 25 20:07:10 CST 2018
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("pocket_asset");
		sql.SET("id = #{record.id,jdbcType=BIGINT}");
		sql.SET("name = #{record.name,jdbcType=VARCHAR}");
		sql.SET("icon = #{record.icon,jdbcType=VARCHAR}");
		sql.SET("contract_account = #{record.contractAccount,jdbcType=VARCHAR}");
		sql.SET("create_date = #{record.createDate,jdbcType=TIMESTAMP}");
		sql.SET("update_date = #{record.updateDate,jdbcType=TIMESTAMP}");
		PocketAssetExample example = (PocketAssetExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pocket_asset
	 * @mbg.generated  Mon Jun 25 20:07:10 CST 2018
	 */
	public String updateByPrimaryKeySelective(PocketAsset record) {
		SQL sql = new SQL();
		sql.UPDATE("pocket_asset");
		if (record.getName() != null) {
			sql.SET("name = #{name,jdbcType=VARCHAR}");
		}
		if (record.getIcon() != null) {
			sql.SET("icon = #{icon,jdbcType=VARCHAR}");
		}
		if (record.getContractAccount() != null) {
			sql.SET("contract_account = #{contractAccount,jdbcType=VARCHAR}");
		}
		if (record.getCreateDate() != null) {
			sql.SET("create_date = #{createDate,jdbcType=TIMESTAMP}");
		}
		if (record.getUpdateDate() != null) {
			sql.SET("update_date = #{updateDate,jdbcType=TIMESTAMP}");
		}
		if (record.getDetail() != null) {
			sql.SET("detail = #{detail,jdbcType=LONGVARCHAR}");
		}
		sql.WHERE("id = #{id,jdbcType=BIGINT}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pocket_asset
	 * @mbg.generated  Mon Jun 25 20:07:10 CST 2018
	 */
	protected void applyWhere(SQL sql, PocketAssetExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}