package it.etoken.base.model.eosblock.entity;

import java.io.Serializable;

public class AccountsKeys implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 3812720864305509215L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_keys.account
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_keys.public_key
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    private String publicKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts_keys.permission
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    private String permission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_keys.account
     *
     * @return the value of accounts_keys.account
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_keys.account
     *
     * @param account the value for accounts_keys.account
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_keys.public_key
     *
     * @return the value of accounts_keys.public_key
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public String getPublicKey() {
        return publicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_keys.public_key
     *
     * @param publicKey the value for accounts_keys.public_key
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts_keys.permission
     *
     * @return the value of accounts_keys.permission
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts_keys.permission
     *
     * @param permission the value for accounts_keys.permission
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }
}