package it.etoken.base.model.eosblock.entity;

import java.io.Serializable;

public class ActionsAccounts implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -8142918415497914502L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actions_accounts.actor
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    private String actor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actions_accounts.permission
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actions_accounts.action_id
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    private Integer actionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actions_accounts.actor
     *
     * @return the value of actions_accounts.actor
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public String getActor() {
        return actor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actions_accounts.actor
     *
     * @param actor the value for actions_accounts.actor
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public void setActor(String actor) {
        this.actor = actor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actions_accounts.permission
     *
     * @return the value of actions_accounts.permission
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actions_accounts.permission
     *
     * @param permission the value for actions_accounts.permission
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actions_accounts.action_id
     *
     * @return the value of actions_accounts.action_id
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public Integer getActionId() {
        return actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actions_accounts.action_id
     *
     * @param actionId the value for actions_accounts.action_id
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public void setActionId(Integer actionId) {
        this.actionId = actionId;
    }
}