package it.etoken.base.model.eosblock.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BlocksExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blocks
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blocks
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blocks
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocks
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public BlocksExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocks
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocks
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocks
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocks
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocks
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocks
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocks
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocks
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocks
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blocks
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table blocks
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBlockNumberIsNull() {
            addCriterion("block_number is null");
            return (Criteria) this;
        }

        public Criteria andBlockNumberIsNotNull() {
            addCriterion("block_number is not null");
            return (Criteria) this;
        }

        public Criteria andBlockNumberEqualTo(Integer value) {
            addCriterion("block_number =", value, "blockNumber");
            return (Criteria) this;
        }

        public Criteria andBlockNumberNotEqualTo(Integer value) {
            addCriterion("block_number <>", value, "blockNumber");
            return (Criteria) this;
        }

        public Criteria andBlockNumberGreaterThan(Integer value) {
            addCriterion("block_number >", value, "blockNumber");
            return (Criteria) this;
        }

        public Criteria andBlockNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("block_number >=", value, "blockNumber");
            return (Criteria) this;
        }

        public Criteria andBlockNumberLessThan(Integer value) {
            addCriterion("block_number <", value, "blockNumber");
            return (Criteria) this;
        }

        public Criteria andBlockNumberLessThanOrEqualTo(Integer value) {
            addCriterion("block_number <=", value, "blockNumber");
            return (Criteria) this;
        }

        public Criteria andBlockNumberIn(List<Integer> values) {
            addCriterion("block_number in", values, "blockNumber");
            return (Criteria) this;
        }

        public Criteria andBlockNumberNotIn(List<Integer> values) {
            addCriterion("block_number not in", values, "blockNumber");
            return (Criteria) this;
        }

        public Criteria andBlockNumberBetween(Integer value1, Integer value2) {
            addCriterion("block_number between", value1, value2, "blockNumber");
            return (Criteria) this;
        }

        public Criteria andBlockNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("block_number not between", value1, value2, "blockNumber");
            return (Criteria) this;
        }

        public Criteria andPrevBlockIdIsNull() {
            addCriterion("prev_block_id is null");
            return (Criteria) this;
        }

        public Criteria andPrevBlockIdIsNotNull() {
            addCriterion("prev_block_id is not null");
            return (Criteria) this;
        }

        public Criteria andPrevBlockIdEqualTo(String value) {
            addCriterion("prev_block_id =", value, "prevBlockId");
            return (Criteria) this;
        }

        public Criteria andPrevBlockIdNotEqualTo(String value) {
            addCriterion("prev_block_id <>", value, "prevBlockId");
            return (Criteria) this;
        }

        public Criteria andPrevBlockIdGreaterThan(String value) {
            addCriterion("prev_block_id >", value, "prevBlockId");
            return (Criteria) this;
        }

        public Criteria andPrevBlockIdGreaterThanOrEqualTo(String value) {
            addCriterion("prev_block_id >=", value, "prevBlockId");
            return (Criteria) this;
        }

        public Criteria andPrevBlockIdLessThan(String value) {
            addCriterion("prev_block_id <", value, "prevBlockId");
            return (Criteria) this;
        }

        public Criteria andPrevBlockIdLessThanOrEqualTo(String value) {
            addCriterion("prev_block_id <=", value, "prevBlockId");
            return (Criteria) this;
        }

        public Criteria andPrevBlockIdLike(String value) {
            addCriterion("prev_block_id like", value, "prevBlockId");
            return (Criteria) this;
        }

        public Criteria andPrevBlockIdNotLike(String value) {
            addCriterion("prev_block_id not like", value, "prevBlockId");
            return (Criteria) this;
        }

        public Criteria andPrevBlockIdIn(List<String> values) {
            addCriterion("prev_block_id in", values, "prevBlockId");
            return (Criteria) this;
        }

        public Criteria andPrevBlockIdNotIn(List<String> values) {
            addCriterion("prev_block_id not in", values, "prevBlockId");
            return (Criteria) this;
        }

        public Criteria andPrevBlockIdBetween(String value1, String value2) {
            addCriterion("prev_block_id between", value1, value2, "prevBlockId");
            return (Criteria) this;
        }

        public Criteria andPrevBlockIdNotBetween(String value1, String value2) {
            addCriterion("prev_block_id not between", value1, value2, "prevBlockId");
            return (Criteria) this;
        }

        public Criteria andIrreversibleIsNull() {
            addCriterion("irreversible is null");
            return (Criteria) this;
        }

        public Criteria andIrreversibleIsNotNull() {
            addCriterion("irreversible is not null");
            return (Criteria) this;
        }

        public Criteria andIrreversibleEqualTo(Boolean value) {
            addCriterion("irreversible =", value, "irreversible");
            return (Criteria) this;
        }

        public Criteria andIrreversibleNotEqualTo(Boolean value) {
            addCriterion("irreversible <>", value, "irreversible");
            return (Criteria) this;
        }

        public Criteria andIrreversibleGreaterThan(Boolean value) {
            addCriterion("irreversible >", value, "irreversible");
            return (Criteria) this;
        }

        public Criteria andIrreversibleGreaterThanOrEqualTo(Boolean value) {
            addCriterion("irreversible >=", value, "irreversible");
            return (Criteria) this;
        }

        public Criteria andIrreversibleLessThan(Boolean value) {
            addCriterion("irreversible <", value, "irreversible");
            return (Criteria) this;
        }

        public Criteria andIrreversibleLessThanOrEqualTo(Boolean value) {
            addCriterion("irreversible <=", value, "irreversible");
            return (Criteria) this;
        }

        public Criteria andIrreversibleIn(List<Boolean> values) {
            addCriterion("irreversible in", values, "irreversible");
            return (Criteria) this;
        }

        public Criteria andIrreversibleNotIn(List<Boolean> values) {
            addCriterion("irreversible not in", values, "irreversible");
            return (Criteria) this;
        }

        public Criteria andIrreversibleBetween(Boolean value1, Boolean value2) {
            addCriterion("irreversible between", value1, value2, "irreversible");
            return (Criteria) this;
        }

        public Criteria andIrreversibleNotBetween(Boolean value1, Boolean value2) {
            addCriterion("irreversible not between", value1, value2, "irreversible");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNull() {
            addCriterion("timestamp is null");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNotNull() {
            addCriterion("timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andTimestampEqualTo(Date value) {
            addCriterion("timestamp =", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotEqualTo(Date value) {
            addCriterion("timestamp <>", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThan(Date value) {
            addCriterion("timestamp >", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("timestamp >=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThan(Date value) {
            addCriterion("timestamp <", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThanOrEqualTo(Date value) {
            addCriterion("timestamp <=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampIn(List<Date> values) {
            addCriterion("timestamp in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotIn(List<Date> values) {
            addCriterion("timestamp not in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampBetween(Date value1, Date value2) {
            addCriterion("timestamp between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotBetween(Date value1, Date value2) {
            addCriterion("timestamp not between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTransactionMerkleRootIsNull() {
            addCriterion("transaction_merkle_root is null");
            return (Criteria) this;
        }

        public Criteria andTransactionMerkleRootIsNotNull() {
            addCriterion("transaction_merkle_root is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionMerkleRootEqualTo(String value) {
            addCriterion("transaction_merkle_root =", value, "transactionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andTransactionMerkleRootNotEqualTo(String value) {
            addCriterion("transaction_merkle_root <>", value, "transactionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andTransactionMerkleRootGreaterThan(String value) {
            addCriterion("transaction_merkle_root >", value, "transactionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andTransactionMerkleRootGreaterThanOrEqualTo(String value) {
            addCriterion("transaction_merkle_root >=", value, "transactionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andTransactionMerkleRootLessThan(String value) {
            addCriterion("transaction_merkle_root <", value, "transactionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andTransactionMerkleRootLessThanOrEqualTo(String value) {
            addCriterion("transaction_merkle_root <=", value, "transactionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andTransactionMerkleRootLike(String value) {
            addCriterion("transaction_merkle_root like", value, "transactionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andTransactionMerkleRootNotLike(String value) {
            addCriterion("transaction_merkle_root not like", value, "transactionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andTransactionMerkleRootIn(List<String> values) {
            addCriterion("transaction_merkle_root in", values, "transactionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andTransactionMerkleRootNotIn(List<String> values) {
            addCriterion("transaction_merkle_root not in", values, "transactionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andTransactionMerkleRootBetween(String value1, String value2) {
            addCriterion("transaction_merkle_root between", value1, value2, "transactionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andTransactionMerkleRootNotBetween(String value1, String value2) {
            addCriterion("transaction_merkle_root not between", value1, value2, "transactionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andActionMerkleRootIsNull() {
            addCriterion("action_merkle_root is null");
            return (Criteria) this;
        }

        public Criteria andActionMerkleRootIsNotNull() {
            addCriterion("action_merkle_root is not null");
            return (Criteria) this;
        }

        public Criteria andActionMerkleRootEqualTo(String value) {
            addCriterion("action_merkle_root =", value, "actionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andActionMerkleRootNotEqualTo(String value) {
            addCriterion("action_merkle_root <>", value, "actionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andActionMerkleRootGreaterThan(String value) {
            addCriterion("action_merkle_root >", value, "actionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andActionMerkleRootGreaterThanOrEqualTo(String value) {
            addCriterion("action_merkle_root >=", value, "actionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andActionMerkleRootLessThan(String value) {
            addCriterion("action_merkle_root <", value, "actionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andActionMerkleRootLessThanOrEqualTo(String value) {
            addCriterion("action_merkle_root <=", value, "actionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andActionMerkleRootLike(String value) {
            addCriterion("action_merkle_root like", value, "actionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andActionMerkleRootNotLike(String value) {
            addCriterion("action_merkle_root not like", value, "actionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andActionMerkleRootIn(List<String> values) {
            addCriterion("action_merkle_root in", values, "actionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andActionMerkleRootNotIn(List<String> values) {
            addCriterion("action_merkle_root not in", values, "actionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andActionMerkleRootBetween(String value1, String value2) {
            addCriterion("action_merkle_root between", value1, value2, "actionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andActionMerkleRootNotBetween(String value1, String value2) {
            addCriterion("action_merkle_root not between", value1, value2, "actionMerkleRoot");
            return (Criteria) this;
        }

        public Criteria andProducerIsNull() {
            addCriterion("producer is null");
            return (Criteria) this;
        }

        public Criteria andProducerIsNotNull() {
            addCriterion("producer is not null");
            return (Criteria) this;
        }

        public Criteria andProducerEqualTo(String value) {
            addCriterion("producer =", value, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerNotEqualTo(String value) {
            addCriterion("producer <>", value, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerGreaterThan(String value) {
            addCriterion("producer >", value, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerGreaterThanOrEqualTo(String value) {
            addCriterion("producer >=", value, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerLessThan(String value) {
            addCriterion("producer <", value, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerLessThanOrEqualTo(String value) {
            addCriterion("producer <=", value, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerLike(String value) {
            addCriterion("producer like", value, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerNotLike(String value) {
            addCriterion("producer not like", value, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerIn(List<String> values) {
            addCriterion("producer in", values, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerNotIn(List<String> values) {
            addCriterion("producer not in", values, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerBetween(String value1, String value2) {
            addCriterion("producer between", value1, value2, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerNotBetween(String value1, String value2) {
            addCriterion("producer not between", value1, value2, "producer");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andNewProducersIsNull() {
            addCriterion("new_producers is null");
            return (Criteria) this;
        }

        public Criteria andNewProducersIsNotNull() {
            addCriterion("new_producers is not null");
            return (Criteria) this;
        }

        public Criteria andNewProducersEqualTo(String value) {
            addCriterion("new_producers =", value, "newProducers");
            return (Criteria) this;
        }

        public Criteria andNewProducersNotEqualTo(String value) {
            addCriterion("new_producers <>", value, "newProducers");
            return (Criteria) this;
        }

        public Criteria andNewProducersGreaterThan(String value) {
            addCriterion("new_producers >", value, "newProducers");
            return (Criteria) this;
        }

        public Criteria andNewProducersGreaterThanOrEqualTo(String value) {
            addCriterion("new_producers >=", value, "newProducers");
            return (Criteria) this;
        }

        public Criteria andNewProducersLessThan(String value) {
            addCriterion("new_producers <", value, "newProducers");
            return (Criteria) this;
        }

        public Criteria andNewProducersLessThanOrEqualTo(String value) {
            addCriterion("new_producers <=", value, "newProducers");
            return (Criteria) this;
        }

        public Criteria andNewProducersLike(String value) {
            addCriterion("new_producers like", value, "newProducers");
            return (Criteria) this;
        }

        public Criteria andNewProducersNotLike(String value) {
            addCriterion("new_producers not like", value, "newProducers");
            return (Criteria) this;
        }

        public Criteria andNewProducersIn(List<String> values) {
            addCriterion("new_producers in", values, "newProducers");
            return (Criteria) this;
        }

        public Criteria andNewProducersNotIn(List<String> values) {
            addCriterion("new_producers not in", values, "newProducers");
            return (Criteria) this;
        }

        public Criteria andNewProducersBetween(String value1, String value2) {
            addCriterion("new_producers between", value1, value2, "newProducers");
            return (Criteria) this;
        }

        public Criteria andNewProducersNotBetween(String value1, String value2) {
            addCriterion("new_producers not between", value1, value2, "newProducers");
            return (Criteria) this;
        }

        public Criteria andNumTransactionsIsNull() {
            addCriterion("num_transactions is null");
            return (Criteria) this;
        }

        public Criteria andNumTransactionsIsNotNull() {
            addCriterion("num_transactions is not null");
            return (Criteria) this;
        }

        public Criteria andNumTransactionsEqualTo(Integer value) {
            addCriterion("num_transactions =", value, "numTransactions");
            return (Criteria) this;
        }

        public Criteria andNumTransactionsNotEqualTo(Integer value) {
            addCriterion("num_transactions <>", value, "numTransactions");
            return (Criteria) this;
        }

        public Criteria andNumTransactionsGreaterThan(Integer value) {
            addCriterion("num_transactions >", value, "numTransactions");
            return (Criteria) this;
        }

        public Criteria andNumTransactionsGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_transactions >=", value, "numTransactions");
            return (Criteria) this;
        }

        public Criteria andNumTransactionsLessThan(Integer value) {
            addCriterion("num_transactions <", value, "numTransactions");
            return (Criteria) this;
        }

        public Criteria andNumTransactionsLessThanOrEqualTo(Integer value) {
            addCriterion("num_transactions <=", value, "numTransactions");
            return (Criteria) this;
        }

        public Criteria andNumTransactionsIn(List<Integer> values) {
            addCriterion("num_transactions in", values, "numTransactions");
            return (Criteria) this;
        }

        public Criteria andNumTransactionsNotIn(List<Integer> values) {
            addCriterion("num_transactions not in", values, "numTransactions");
            return (Criteria) this;
        }

        public Criteria andNumTransactionsBetween(Integer value1, Integer value2) {
            addCriterion("num_transactions between", value1, value2, "numTransactions");
            return (Criteria) this;
        }

        public Criteria andNumTransactionsNotBetween(Integer value1, Integer value2) {
            addCriterion("num_transactions not between", value1, value2, "numTransactions");
            return (Criteria) this;
        }

        public Criteria andConfirmedIsNull() {
            addCriterion("confirmed is null");
            return (Criteria) this;
        }

        public Criteria andConfirmedIsNotNull() {
            addCriterion("confirmed is not null");
            return (Criteria) this;
        }

        public Criteria andConfirmedEqualTo(Integer value) {
            addCriterion("confirmed =", value, "confirmed");
            return (Criteria) this;
        }

        public Criteria andConfirmedNotEqualTo(Integer value) {
            addCriterion("confirmed <>", value, "confirmed");
            return (Criteria) this;
        }

        public Criteria andConfirmedGreaterThan(Integer value) {
            addCriterion("confirmed >", value, "confirmed");
            return (Criteria) this;
        }

        public Criteria andConfirmedGreaterThanOrEqualTo(Integer value) {
            addCriterion("confirmed >=", value, "confirmed");
            return (Criteria) this;
        }

        public Criteria andConfirmedLessThan(Integer value) {
            addCriterion("confirmed <", value, "confirmed");
            return (Criteria) this;
        }

        public Criteria andConfirmedLessThanOrEqualTo(Integer value) {
            addCriterion("confirmed <=", value, "confirmed");
            return (Criteria) this;
        }

        public Criteria andConfirmedIn(List<Integer> values) {
            addCriterion("confirmed in", values, "confirmed");
            return (Criteria) this;
        }

        public Criteria andConfirmedNotIn(List<Integer> values) {
            addCriterion("confirmed not in", values, "confirmed");
            return (Criteria) this;
        }

        public Criteria andConfirmedBetween(Integer value1, Integer value2) {
            addCriterion("confirmed between", value1, value2, "confirmed");
            return (Criteria) this;
        }

        public Criteria andConfirmedNotBetween(Integer value1, Integer value2) {
            addCriterion("confirmed not between", value1, value2, "confirmed");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table blocks
     *
     * @mbg.generated do_not_delete_during_merge Tue Jul 10 16:13:42 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table blocks
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}