package it.etoken.base.model.eosblock.entity;

import java.io.Serializable;
import java.util.Date;

public class Transactions implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -3769082016671358191L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.id
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.block_id
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    private Integer blockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.ref_block_num
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    private Integer refBlockNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.ref_block_prefix
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    private Integer refBlockPrefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.expiration
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    private Date expiration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.pending
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    private Boolean pending;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.created_at
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.num_actions
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    private Integer numActions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transactions.updated_at
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.id
     *
     * @return the value of transactions.id
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.id
     *
     * @param id the value for transactions.id
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.block_id
     *
     * @return the value of transactions.block_id
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public Integer getBlockId() {
        return blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.block_id
     *
     * @param blockId the value for transactions.block_id
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public void setBlockId(Integer blockId) {
        this.blockId = blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.ref_block_num
     *
     * @return the value of transactions.ref_block_num
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public Integer getRefBlockNum() {
        return refBlockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.ref_block_num
     *
     * @param refBlockNum the value for transactions.ref_block_num
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public void setRefBlockNum(Integer refBlockNum) {
        this.refBlockNum = refBlockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.ref_block_prefix
     *
     * @return the value of transactions.ref_block_prefix
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public Integer getRefBlockPrefix() {
        return refBlockPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.ref_block_prefix
     *
     * @param refBlockPrefix the value for transactions.ref_block_prefix
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public void setRefBlockPrefix(Integer refBlockPrefix) {
        this.refBlockPrefix = refBlockPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.expiration
     *
     * @return the value of transactions.expiration
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public Date getExpiration() {
        return expiration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.expiration
     *
     * @param expiration the value for transactions.expiration
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public void setExpiration(Date expiration) {
        this.expiration = expiration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.pending
     *
     * @return the value of transactions.pending
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public Boolean getPending() {
        return pending;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.pending
     *
     * @param pending the value for transactions.pending
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public void setPending(Boolean pending) {
        this.pending = pending;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.created_at
     *
     * @return the value of transactions.created_at
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.created_at
     *
     * @param createdAt the value for transactions.created_at
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.num_actions
     *
     * @return the value of transactions.num_actions
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public Integer getNumActions() {
        return numActions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.num_actions
     *
     * @param numActions the value for transactions.num_actions
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public void setNumActions(Integer numActions) {
        this.numActions = numActions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transactions.updated_at
     *
     * @return the value of transactions.updated_at
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transactions.updated_at
     *
     * @param updatedAt the value for transactions.updated_at
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}