package it.etoken.base.model.eosblock.entity;

import java.io.Serializable;

public class Votes implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 3670779068162920284L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votes.account
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votes.votes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    private String votes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votes.account
     *
     * @return the value of votes.account
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votes.account
     *
     * @param account the value for votes.account
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votes.votes
     *
     * @return the value of votes.votes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public String getVotes() {
        return votes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votes.votes
     *
     * @param votes the value for votes.votes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public void setVotes(String votes) {
        this.votes = votes;
    }
}