package it.etoken.base.model.user.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class EosAccountOrder implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -8456958431762320145L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eos_account_order.id
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eos_account_order.order_no
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eos_account_order.status
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eos_account_order.uid
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eos_account_order.username
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eos_account_order.amount
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eos_account_order.ram
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    private Long ram;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eos_account_order.cpu
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    private Long cpu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eos_account_order.net
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    private Long net;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eos_account_order.account_name
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eos_account_order.public_key
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    private String publicKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eos_account_order.createdate
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eos_account_order.updatedate
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eos_account_order.id
     *
     * @return the value of eos_account_order.id
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eos_account_order.id
     *
     * @param id the value for eos_account_order.id
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eos_account_order.order_no
     *
     * @return the value of eos_account_order.order_no
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eos_account_order.order_no
     *
     * @param orderNo the value for eos_account_order.order_no
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eos_account_order.status
     *
     * @return the value of eos_account_order.status
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eos_account_order.status
     *
     * @param status the value for eos_account_order.status
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eos_account_order.uid
     *
     * @return the value of eos_account_order.uid
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eos_account_order.uid
     *
     * @param uid the value for eos_account_order.uid
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eos_account_order.username
     *
     * @return the value of eos_account_order.username
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eos_account_order.username
     *
     * @param username the value for eos_account_order.username
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eos_account_order.amount
     *
     * @return the value of eos_account_order.amount
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eos_account_order.amount
     *
     * @param amount the value for eos_account_order.amount
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eos_account_order.ram
     *
     * @return the value of eos_account_order.ram
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public Long getRam() {
        return ram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eos_account_order.ram
     *
     * @param ram the value for eos_account_order.ram
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public void setRam(Long ram) {
        this.ram = ram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eos_account_order.cpu
     *
     * @return the value of eos_account_order.cpu
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public Long getCpu() {
        return cpu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eos_account_order.cpu
     *
     * @param cpu the value for eos_account_order.cpu
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public void setCpu(Long cpu) {
        this.cpu = cpu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eos_account_order.net
     *
     * @return the value of eos_account_order.net
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public Long getNet() {
        return net;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eos_account_order.net
     *
     * @param net the value for eos_account_order.net
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public void setNet(Long net) {
        this.net = net;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eos_account_order.account_name
     *
     * @return the value of eos_account_order.account_name
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eos_account_order.account_name
     *
     * @param accountName the value for eos_account_order.account_name
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eos_account_order.public_key
     *
     * @return the value of eos_account_order.public_key
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public String getPublicKey() {
        return publicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eos_account_order.public_key
     *
     * @param publicKey the value for eos_account_order.public_key
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eos_account_order.createdate
     *
     * @return the value of eos_account_order.createdate
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eos_account_order.createdate
     *
     * @param createdate the value for eos_account_order.createdate
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eos_account_order.updatedate
     *
     * @return the value of eos_account_order.updatedate
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eos_account_order.updatedate
     *
     * @param updatedate the value for eos_account_order.updatedate
     *
     * @mbg.generated Mon Jul 09 16:58:56 CST 2018
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}