package it.etoken.base.model.user.entity;

import java.util.Date;

public class UserSigninLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_signin_log.id
     *
     * @mbg.generated Tue May 22 18:15:17 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_signin_log.uid
     *
     * @mbg.generated Tue May 22 18:15:17 CST 2018
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_signin_log.nickname
     *
     * @mbg.generated Tue May 22 18:15:17 CST 2018
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_signin_log.signdate
     *
     * @mbg.generated Tue May 22 18:15:17 CST 2018
     */
    private Date signdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_signin_log.createdate
     *
     * @mbg.generated Tue May 22 18:15:17 CST 2018
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_signin_log.id
     *
     * @return the value of user_signin_log.id
     *
     * @mbg.generated Tue May 22 18:15:17 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_signin_log.id
     *
     * @param id the value for user_signin_log.id
     *
     * @mbg.generated Tue May 22 18:15:17 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_signin_log.uid
     *
     * @return the value of user_signin_log.uid
     *
     * @mbg.generated Tue May 22 18:15:17 CST 2018
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_signin_log.uid
     *
     * @param uid the value for user_signin_log.uid
     *
     * @mbg.generated Tue May 22 18:15:17 CST 2018
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_signin_log.nickname
     *
     * @return the value of user_signin_log.nickname
     *
     * @mbg.generated Tue May 22 18:15:17 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_signin_log.nickname
     *
     * @param nickname the value for user_signin_log.nickname
     *
     * @mbg.generated Tue May 22 18:15:17 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_signin_log.signdate
     *
     * @return the value of user_signin_log.signdate
     *
     * @mbg.generated Tue May 22 18:15:17 CST 2018
     */
    public Date getSigndate() {
        return signdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_signin_log.signdate
     *
     * @param signdate the value for user_signin_log.signdate
     *
     * @mbg.generated Tue May 22 18:15:17 CST 2018
     */
    public void setSigndate(Date signdate) {
        this.signdate = signdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_signin_log.createdate
     *
     * @return the value of user_signin_log.createdate
     *
     * @mbg.generated Tue May 22 18:15:17 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_signin_log.createdate
     *
     * @param createdate the value for user_signin_log.createdate
     *
     * @mbg.generated Tue May 22 18:15:17 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}