package it.etoken.base.model.market.entity;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class EosElector implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eos_elector.id
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eos_elector.name
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eos_elector.account
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eos_elector.icon
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	private String icon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eos_elector.region
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	private String region;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eos_elector.url
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eos_elector.createdate
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eos_elector.modifydate
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	private Date modifydate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eos_elector.deleted
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	private Integer deleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column eos_elector.introduce
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	private String introduce;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eos_elector.id
	 * @return  the value of eos_elector.id
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eos_elector.id
	 * @param id  the value for eos_elector.id
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eos_elector.name
	 * @return  the value of eos_elector.name
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eos_elector.name
	 * @param name  the value for eos_elector.name
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eos_elector.account
	 * @return  the value of eos_elector.account
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eos_elector.account
	 * @param account  the value for eos_elector.account
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eos_elector.icon
	 * @return  the value of eos_elector.icon
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eos_elector.icon
	 * @param icon  the value for eos_elector.icon
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eos_elector.region
	 * @return  the value of eos_elector.region
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	public String getRegion() {
		return region;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eos_elector.region
	 * @param region  the value for eos_elector.region
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	public void setRegion(String region) {
		this.region = region;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eos_elector.url
	 * @return  the value of eos_elector.url
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eos_elector.url
	 * @param url  the value for eos_elector.url
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eos_elector.createdate
	 * @return  the value of eos_elector.createdate
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eos_elector.createdate
	 * @param createdate  the value for eos_elector.createdate
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eos_elector.modifydate
	 * @return  the value of eos_elector.modifydate
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	public Date getModifydate() {
		return modifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eos_elector.modifydate
	 * @param modifydate  the value for eos_elector.modifydate
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eos_elector.deleted
	 * @return  the value of eos_elector.deleted
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	public Integer getDeleted() {
		return deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eos_elector.deleted
	 * @param deleted  the value for eos_elector.deleted
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column eos_elector.introduce
	 * @return  the value of eos_elector.introduce
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	public String getIntroduce() {
		return introduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column eos_elector.introduce
	 * @param introduce  the value for eos_elector.introduce
	 * @mbg.generated  Mon Jun 11 16:58:24 CST 2018
	 */
	public void setIntroduce(String introduce) {
		this.introduce = introduce;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -7930144004715017234L;
}