package it.etoken.component.eosblock.dao.provider;

import it.etoken.base.model.eosblock.entity.Stakes;
import it.etoken.base.model.eosblock.entity.StakesExample.Criteria;
import it.etoken.base.model.eosblock.entity.StakesExample.Criterion;
import it.etoken.base.model.eosblock.entity.StakesExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class StakesSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stakes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public String countByExample(StakesExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("stakes");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stakes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public String deleteByExample(StakesExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("stakes");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stakes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public String insertSelective(Stakes record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("stakes");
        
        if (record.getAccount() != null) {
            sql.VALUES("account", "#{account,jdbcType=VARCHAR}");
        }
        
        if (record.getCpu() != null) {
            sql.VALUES("cpu", "#{cpu,jdbcType=DOUBLE}");
        }
        
        if (record.getNet() != null) {
            sql.VALUES("net", "#{net,jdbcType=DOUBLE}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stakes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public String selectByExample(StakesExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("account");
        } else {
            sql.SELECT("account");
        }
        sql.SELECT("cpu");
        sql.SELECT("net");
        sql.FROM("stakes");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stakes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Stakes record = (Stakes) parameter.get("record");
        StakesExample example = (StakesExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("stakes");
        
        if (record.getAccount() != null) {
            sql.SET("account = #{record.account,jdbcType=VARCHAR}");
        }
        
        if (record.getCpu() != null) {
            sql.SET("cpu = #{record.cpu,jdbcType=DOUBLE}");
        }
        
        if (record.getNet() != null) {
            sql.SET("net = #{record.net,jdbcType=DOUBLE}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stakes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("stakes");
        
        sql.SET("account = #{record.account,jdbcType=VARCHAR}");
        sql.SET("cpu = #{record.cpu,jdbcType=DOUBLE}");
        sql.SET("net = #{record.net,jdbcType=DOUBLE}");
        
        StakesExample example = (StakesExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stakes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    public String updateByPrimaryKeySelective(Stakes record) {
        SQL sql = new SQL();
        sql.UPDATE("stakes");
        
        if (record.getCpu() != null) {
            sql.SET("cpu = #{cpu,jdbcType=DOUBLE}");
        }
        
        if (record.getNet() != null) {
            sql.SET("net = #{net,jdbcType=DOUBLE}");
        }
        
        sql.WHERE("account = #{account,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stakes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    protected void applyWhere(SQL sql, StakesExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}