package it.etoken.component.eosblock.dao.mapper;

import it.etoken.base.model.eosblock.entity.AccountsKeys;
import it.etoken.base.model.eosblock.entity.AccountsKeysExample;
import it.etoken.component.eosblock.dao.provider.AccountsKeysSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
@Mapper
public interface AccountsKeysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts_keys
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @SelectProvider(type=AccountsKeysSqlProvider.class, method="countByExample")
    long countByExample(AccountsKeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts_keys
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @DeleteProvider(type=AccountsKeysSqlProvider.class, method="deleteByExample")
    int deleteByExample(AccountsKeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts_keys
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @Insert({
        "insert into accounts_keys (account, public_key, ",
        "permission)",
        "values (#{account,jdbcType=VARCHAR}, #{publicKey,jdbcType=VARCHAR}, ",
        "#{permission,jdbcType=VARCHAR})"
    })
    int insert(AccountsKeys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts_keys
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @InsertProvider(type=AccountsKeysSqlProvider.class, method="insertSelective")
    int insertSelective(AccountsKeys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts_keys
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @SelectProvider(type=AccountsKeysSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="account", property="account", jdbcType=JdbcType.VARCHAR),
        @Result(column="public_key", property="publicKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="permission", property="permission", jdbcType=JdbcType.VARCHAR)
    })
    List<AccountsKeys> selectByExample(AccountsKeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts_keys
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @UpdateProvider(type=AccountsKeysSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AccountsKeys record, @Param("example") AccountsKeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts_keys
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @UpdateProvider(type=AccountsKeysSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AccountsKeys record, @Param("example") AccountsKeysExample example);
}