package it.etoken.component.eosblock.dao.mapper;

import it.etoken.base.model.eosblock.entity.Actions;
import it.etoken.base.model.eosblock.entity.ActionsExample;
import it.etoken.component.eosblock.dao.provider.ActionsSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
@Mapper
public interface ActionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @SelectProvider(type=ActionsSqlProvider.class, method="countByExample")
    long countByExample(ActionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @DeleteProvider(type=ActionsSqlProvider.class, method="deleteByExample")
    int deleteByExample(ActionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @Delete({
        "delete from actions",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @Insert({
        "insert into actions (id, account, ",
        "transaction_id, seq, ",
        "parent, name, created_at, ",
        "data)",
        "values (#{id,jdbcType=INTEGER}, #{account,jdbcType=VARCHAR}, ",
        "#{transactionId,jdbcType=VARCHAR}, #{seq,jdbcType=SMALLINT}, ",
        "#{parent,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{data,jdbcType=CHAR})"
    })
    int insert(Actions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @InsertProvider(type=ActionsSqlProvider.class, method="insertSelective")
    int insertSelective(Actions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @SelectProvider(type=ActionsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="account", property="account", jdbcType=JdbcType.VARCHAR),
        @Result(column="transaction_id", property="transactionId", jdbcType=JdbcType.VARCHAR),
        @Result(column="seq", property="seq", jdbcType=JdbcType.SMALLINT),
        @Result(column="parent", property="parent", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="data", property="data", jdbcType=JdbcType.CHAR)
    })
    List<Actions> selectByExample(ActionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @Select({
        "select",
        "id, account, transaction_id, seq, parent, name, created_at, data",
        "from actions",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="account", property="account", jdbcType=JdbcType.VARCHAR),
        @Result(column="transaction_id", property="transactionId", jdbcType=JdbcType.VARCHAR),
        @Result(column="seq", property="seq", jdbcType=JdbcType.SMALLINT),
        @Result(column="parent", property="parent", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="data", property="data", jdbcType=JdbcType.CHAR)
    })
    Actions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @UpdateProvider(type=ActionsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Actions record, @Param("example") ActionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @UpdateProvider(type=ActionsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Actions record, @Param("example") ActionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @UpdateProvider(type=ActionsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Actions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @Update({
        "update actions",
        "set account = #{account,jdbcType=VARCHAR},",
          "transaction_id = #{transactionId,jdbcType=VARCHAR},",
          "seq = #{seq,jdbcType=SMALLINT},",
          "parent = #{parent,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "data = #{data,jdbcType=CHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Actions record);
}