package it.etoken.component.eosblock.dao.mapper;

import it.etoken.base.model.eosblock.entity.ActionsAccounts;
import it.etoken.base.model.eosblock.entity.ActionsAccountsExample;
import it.etoken.component.eosblock.dao.provider.ActionsAccountsSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
@Mapper
public interface ActionsAccountsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions_accounts
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @SelectProvider(type=ActionsAccountsSqlProvider.class, method="countByExample")
    long countByExample(ActionsAccountsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions_accounts
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @DeleteProvider(type=ActionsAccountsSqlProvider.class, method="deleteByExample")
    int deleteByExample(ActionsAccountsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions_accounts
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @Insert({
        "insert into actions_accounts (actor, permission, ",
        "action_id)",
        "values (#{actor,jdbcType=VARCHAR}, #{permission,jdbcType=VARCHAR}, ",
        "#{actionId,jdbcType=INTEGER})"
    })
    int insert(ActionsAccounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions_accounts
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @InsertProvider(type=ActionsAccountsSqlProvider.class, method="insertSelective")
    int insertSelective(ActionsAccounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions_accounts
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @SelectProvider(type=ActionsAccountsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="actor", property="actor", jdbcType=JdbcType.VARCHAR),
        @Result(column="permission", property="permission", jdbcType=JdbcType.VARCHAR),
        @Result(column="action_id", property="actionId", jdbcType=JdbcType.INTEGER)
    })
    List<ActionsAccounts> selectByExample(ActionsAccountsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions_accounts
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @UpdateProvider(type=ActionsAccountsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ActionsAccounts record, @Param("example") ActionsAccountsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions_accounts
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @UpdateProvider(type=ActionsAccountsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ActionsAccounts record, @Param("example") ActionsAccountsExample example);
}