package it.etoken.component.eosblock.dao.mapper;

import it.etoken.base.model.eosblock.entity.Stakes;
import it.etoken.base.model.eosblock.entity.StakesExample;
import it.etoken.component.eosblock.dao.provider.StakesSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
@Mapper
public interface StakesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stakes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @SelectProvider(type=StakesSqlProvider.class, method="countByExample")
    long countByExample(StakesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stakes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @DeleteProvider(type=StakesSqlProvider.class, method="deleteByExample")
    int deleteByExample(StakesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stakes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @Delete({
        "delete from stakes",
        "where account = #{account,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String account);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stakes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @Insert({
        "insert into stakes (account, cpu, ",
        "net)",
        "values (#{account,jdbcType=VARCHAR}, #{cpu,jdbcType=DOUBLE}, ",
        "#{net,jdbcType=DOUBLE})"
    })
    int insert(Stakes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stakes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @InsertProvider(type=StakesSqlProvider.class, method="insertSelective")
    int insertSelective(Stakes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stakes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @SelectProvider(type=StakesSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="account", property="account", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="cpu", property="cpu", jdbcType=JdbcType.DOUBLE),
        @Result(column="net", property="net", jdbcType=JdbcType.DOUBLE)
    })
    List<Stakes> selectByExample(StakesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stakes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @Select({
        "select",
        "account, cpu, net",
        "from stakes",
        "where account = #{account,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="account", property="account", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="cpu", property="cpu", jdbcType=JdbcType.DOUBLE),
        @Result(column="net", property="net", jdbcType=JdbcType.DOUBLE)
    })
    Stakes selectByPrimaryKey(String account);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stakes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @UpdateProvider(type=StakesSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Stakes record, @Param("example") StakesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stakes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @UpdateProvider(type=StakesSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Stakes record, @Param("example") StakesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stakes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @UpdateProvider(type=StakesSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Stakes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stakes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @Update({
        "update stakes",
        "set cpu = #{cpu,jdbcType=DOUBLE},",
          "net = #{net,jdbcType=DOUBLE}",
        "where account = #{account,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Stakes record);
}