package it.etoken.component.eosblock.dao.mapper;

import it.etoken.base.model.eosblock.entity.Votes;
import it.etoken.base.model.eosblock.entity.VotesExample;
import it.etoken.component.eosblock.dao.provider.VotesSqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
@Mapper
public interface VotesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @SelectProvider(type=VotesSqlProvider.class, method="countByExample")
    long countByExample(VotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @DeleteProvider(type=VotesSqlProvider.class, method="deleteByExample")
    int deleteByExample(VotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @Delete({
        "delete from votes",
        "where account = #{account,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String account);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @Insert({
        "insert into votes (account, votes)",
        "values (#{account,jdbcType=VARCHAR}, #{votes,jdbcType=CHAR})"
    })
    int insert(Votes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @InsertProvider(type=VotesSqlProvider.class, method="insertSelective")
    int insertSelective(Votes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @SelectProvider(type=VotesSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="account", property="account", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="votes", property="votes", jdbcType=JdbcType.CHAR)
    })
    List<Votes> selectByExample(VotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @Select({
        "select",
        "account, votes",
        "from votes",
        "where account = #{account,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="account", property="account", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="votes", property="votes", jdbcType=JdbcType.CHAR)
    })
    Votes selectByPrimaryKey(String account);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @UpdateProvider(type=VotesSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Votes record, @Param("example") VotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @UpdateProvider(type=VotesSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Votes record, @Param("example") VotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @UpdateProvider(type=VotesSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Votes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votes
     *
     * @mbg.generated Tue Jul 10 16:13:42 CST 2018
     */
    @Update({
        "update votes",
        "set votes = #{votes,jdbcType=CHAR}",
        "where account = #{account,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Votes record);
}