package it.etoken.base.model.news.entity;

import java.io.Serializable;
import java.util.Date;

import it.etoken.base.model.BaseEntity;

public class JobManager implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 2383433174164866746L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_manager.id
     *
     * @mbg.generated Thu Jun 28 18:57:26 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_manager.job_name
     *
     * @mbg.generated Thu Jun 28 18:57:26 CST 2018
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_manager.status
     *
     * @mbg.generated Thu Jun 28 18:57:26 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_manager.createdate
     *
     * @mbg.generated Thu Jun 28 18:57:26 CST 2018
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_manager.modifydate
     *
     * @mbg.generated Thu Jun 28 18:57:26 CST 2018
     */
    private Date modifydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_manager.id
     *
     * @return the value of job_manager.id
     *
     * @mbg.generated Thu Jun 28 18:57:26 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_manager.id
     *
     * @param id the value for job_manager.id
     *
     * @mbg.generated Thu Jun 28 18:57:26 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_manager.job_name
     *
     * @return the value of job_manager.job_name
     *
     * @mbg.generated Thu Jun 28 18:57:26 CST 2018
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_manager.job_name
     *
     * @param jobName the value for job_manager.job_name
     *
     * @mbg.generated Thu Jun 28 18:57:26 CST 2018
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_manager.status
     *
     * @return the value of job_manager.status
     *
     * @mbg.generated Thu Jun 28 18:57:26 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_manager.status
     *
     * @param status the value for job_manager.status
     *
     * @mbg.generated Thu Jun 28 18:57:26 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_manager.createdate
     *
     * @return the value of job_manager.createdate
     *
     * @mbg.generated Thu Jun 28 18:57:26 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_manager.createdate
     *
     * @param createdate the value for job_manager.createdate
     *
     * @mbg.generated Thu Jun 28 18:57:26 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_manager.modifydate
     *
     * @return the value of job_manager.modifydate
     *
     * @mbg.generated Thu Jun 28 18:57:26 CST 2018
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_manager.modifydate
     *
     * @param modifydate the value for job_manager.modifydate
     *
     * @mbg.generated Thu Jun 28 18:57:26 CST 2018
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }
}